### ISSUE TITLE
Cannot place item-frames and signs on Dispensers, Chests, etc.

### ISSUE THREAD

**Issue by MeAngel** [nsporillo/entitymanager#2]
When EntityManager is enabled, I'm not able to shift-click to add signs or item frames to block like dispensers, chests, etc. 

When I disable it, I'm able to do these things. 

It's not clear in the config files where to prevent this from happening. 

Thanks for any help

**Comment by nsporillo** [comment]
Is this with default config?

EM handles interact events so it's possible if you're holding a item that is disabled from interaction, you can't use it on a chest.

Thanks for making an issue on the tracker btw.

**Comment by MeAngel** [comment]
Yes I believe so. I disabled a few other suspect plugins and tried to place
the items and wasn't able and then when i tried EntityManager. I deleted
the directory and I think the jar too and have nothing but the default
configs that were generated for each of my worlds and it was the same.

Thanks for your help! I hope you have a good 2016!

**Comment by nsporillo** [comment]
Just tested this and was able to place a sign on a dispenser with and without OP.

I was only disallowed when Worldguard prevented me from opening the dispenser in a region.

So can you post your console logs beginning with startup and when you interact with something and it doesnt let you. Also include any in-game messages that appear if they do.

Thanks,
